2019-03-24 13:00:14 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method MemoryUsage.engine_started of <scrapy.extensions.memusage.MemoryUsage object at 0x0000000004D8D7B8>>
Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "F:\Anaconda3\lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "F:\Anaconda3\lib\site-packages\scrapy\extensions\memusage.py", line 55, in engine_started
    self.crawler.stats.set_value('memusage/startup', self.get_virtual_size())
  File "F:\Anaconda3\lib\site-packages\scrapy\extensions\memusage.py", line 48, in get_virtual_size
    size = self.resource.getrusage(self.resource.RUSAGE_SELF).ru_maxrss
AttributeError: module 'resource' has no attribute 'getrusage'
2019-03-24 13:00:15 [scrapy.core.scraper] ERROR: Spider error processing <GET https://zj.lianjia.com/ershoufang/yangzhongshi/> (referer: https://zj.lianjia.com/ershoufang/)
Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "F:\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "F:\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "F:\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "F:\Anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "F:\Python_work\MyScrapy\lianjia\lianjia\spiders\lianjiahouse.py", line 33, in parse_navi_url
    totalpg = int(rex.findall(body_data)[0])
IndexError: list index out of range
2019-03-24 13:15:27 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method MemoryUsage.engine_stopped of <scrapy.extensions.memusage.MemoryUsage object at 0x0000000004D8D7B8>>
Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "F:\Anaconda3\lib\site-packages\pydispatch\robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "F:\Anaconda3\lib\site-packages\scrapy\extensions\memusage.py", line 70, in engine_stopped
    for tsk in self.tasks:
AttributeError: 'MemoryUsage' object has no attribute 'tasks'
